### ISSUE TITLE
Fails to detect displays on System76 Pop!_OS 22.04

### ISSUE THREAD

**Issue by wmchristie** [haimgel/display-switch#103]
The laptop has a hybrid graphic system which uses an NVIDIA GPU for external monitors.
The systemctl log shows
```
Did not detect any DDC-compatible displays!
```
I tried various cfg feature keys on the ddc-hi with Cargo to see if I could turn on the nvapi, but failed and gave up after it appeared that it's likely that code will only work on Windows.
I have worked around the problem by installing display-switch on the Windows 10 machine and using both on_usb_connect and on_usb_disconnect.

**Comment by haimgel** [comment]
I don't think we can do anything about it here. The `ddc`  crate and/or its dependencies might be able to address it, though.
