### ISSUE TITLE
Doesn't open on Windows 

### ISSUE THREAD

**Issue by oakif** [haimgel/display-switch#106]
I installed Rust and hoped that I could install the binary. Well, it seems like I was able to get it compiled but it doesn't even open, although I created a configuration file. I don't see any logs either--I just see a blank file. 

Any suggestions for what I could do? Would love some binaries but it seems like there are none available right now. The last ones have expired

**Comment by isrbaral** [comment]
Best way to troubleshoot is to run it from cmd, it'll output any startup error it's experiencing. 
Unfortunately, this is a difficult problem to solve and kinda niche so there isn't any great software out there. The UX for this obviously isn't super polished, and seeing as the last update was nearly a year ago, I wouldn't expect much support as the main dev appears to be too busy atm.
