### ISSUE TITLE
main branch build fails with --locked because version differs between Cargo.toml and Cargo.lock

### ISSUE THREAD

**Issue by leodag** [haimgel/display-switch#107]
#99 has [updated the version of display_switch to 1.2.0 in `Cargo.lock`](https://github.com/haimgel/display-switch/blob/e5edc0c/Cargo.lock#L207), but not in `Cargo.toml`. As such, building with `cargo build --locked` show the following message:

```
error: the lock file <...>/display-switch/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

If they are made to match, everything goes as expected.

**Comment by haimgel** [comment]
Thank you for flagging this, it's now fixed.
