### ISSUE TITLE
DDC error, even though I am not even trying to control a DDC monitor

### ISSUE THREAD

**Issue by MatthiasGrandl** [haimgel/display-switch#108]
Small suggestion: Would it be possible to skip the DDC check if the user is exclusively using `on_usb_connect_execute` and `on_usb_disconnect_execute`? My TV does not support DDC and I built a script to control it over it's API, but `display_switch` does not seem to support this usecase as I get the following: `14:38:53 [ERROR] Did not detect any DDC-compatible displays!`

**Comment by haimgel** [comment]
I suggest trying some other software to trigger actions on USB connection/disconnection.
