### ISSUE TITLE
Dual display setup with unconfigured monitor throwing an error

### ISSUE THREAD

**Issue by ajbucci** [haimgel/display-switch#109]
I have a dual display setup where only one monitor supports input switching with DDC. In my config I specify the working monitor only, but my other monitor is throwing an error with ddc (on arch/wayland/nvidia proprietary drivers) which stops all further execution. For whatever reason the display-switch and config function as-expected on Windows.

Here's the error:

> 17:25:28 [ERROR] Failed to get current input for display 'ACI ROG PG279Q #ASMbKcVRyend': DDC/CI I2C error: Input/output error (os error 5)

Here's my config:

> usb_device = "0483:502b"
> 
> [monitor1]
> monitor_id = "dell"
> on_usb_connect = "DisplayPort1"
> on_usb_disconnect = "Hdmi2"

I can confirm that display switching is working as-expected using ddcutil and already have a workaround in place to perform the input switching using udev rules.

I'm not very familiar with rust, but it looks like the way it's currently coded should be throwing a warning and not stopping all execution? Any ideas?

**Comment by bukhamsin** [comment]
Did you ever find a solution for this? I am getting the same error.

**Comment by ajbucci** [comment]
> Did you ever find a solution for this? I am getting the same error.

I didn't, though I haven't tried it in a while. I'm now using udev rules with ddcutil to do the switching.
