### ISSUE TITLE
Daisy chaining 2 displays with only 1 that supports DDC drops the second monitor when changing 

### ISSUE THREAD

**Issue by marouamghar** [haimgel/display-switch#113]
I have 1 lenovo thinkvision P24q-10 that is DDC compatible. I am able to switch back and forth without issues. However, it is daisy-chaining to another non compatible screen. Whenever I switch, the connection is dropped, and the new computer does not recognize the second monitor, as if it was not connected at all. Switching manually the 1st monitor using its settings works correctly, both monitors connect to the computers. I am not able to figure out if the issue comes from the monitor itself or the software, but since it works using a different way, i am leaning towards the software.
Thanks !

**Comment by haimgel** [comment]
Hard to say whether it's hardware (firmware) or software, _anything_ that talks DDC to displays hits [all kinds of corner cases and weird bugs](https://notes.alinpanaitiu.com/Weird%20monitor%20bugs) in firmware... I suggest: try to control your screens with something other than `display-switch` and see what happens. There are many apps like that, [ddccontrol](https://github.com/ddccontrol/ddccontrol), for example.

**Comment by marouamghar** [comment]
Thanks for the response. I did try another windows tool, and i am encountering the same issue. I suppose it means a deeper problem is there. I wasn't able where to report it though. Is there like a parent repo for DDC commands?

**Comment by haimgel** [comment]
I think the most probable source for this issue is your monitor's firmware, you could report this to the manufacturer. I don't have high hopes for them fixing the issue, though.
