### ISSUE TITLE
[Question] I'm considering user-friendly crossplatform UI. Anything already in the works?

### ISSUE THREAD

**Issue by alexVinarskis** [haimgel/display-switch#118]
As title suggest, I'm considering cross-platform Flutter based user-friendly configuration UI, so that average user can install the app and just select options from UI. 

My idea would be to include this repo, as well as my own k[eycombo-controlled](https://github.com/alexVinarskis/display-switch-keycombo) redesign as sub modules for UI/installer, so that user can install it as any other app. The fronted will then install services, and allow to edit `.ini` from front end via say check boxes/drop down menu. 

Wondering if you had any ideas/plans for this already, or if potentially something like that is already in the works. Wouldn't want to re-invent the wheel :)

**Comment by JakeAlmer** [comment]
https://github.com/fiddyschmitt/SimpleKVM is a related UI

**Comment by haimgel** [comment]
I don't have anything of the sort planned. Moreover, I probably won't accept patches that add UI components to the app: I think it's perfectly fine to run it headless and not have an icon or any other desktop presence.

However: I will accept patches that make this command-line app easier to integrate with other apps (e.g. additional command-line options if needed, better / easier to parse error messages, etc.)
