### ISSUE TITLE
1.3.0 on Windows doesn't detect USB changes

### ISSUE THREAD

**Issue by sagacity** [haimgel/display-switch#128]
Disclaimer: First time user of your tool, so I may be imagining things :)

Version 1.3.0 of `display_switch` doesn't seem to detect any USB changes, at least on Windows 11. Nothing shows up in the logs (even with debug logging enabled via `RUST_LOG=debug`).

Version 1.2.0 works fine with logging like `09:58:55 [DEBUG] (1) display_switch::app: Detected device change. Removed device: "0bda:5412"`.

I haven't spent any time on bisecting dependencies to figure out what's going on, but happy to assist if you cannot reproduce the issue.

**Comment by chris400** [comment]
For me 1.3.0 does not detect changes on Windows 10 either.

1.2.0 works fine on both Windows 10 and Windows 11.

**Comment by haimgel** [comment]
Confirm the bug, I can replicate it. Looking into it this week.
