### ISSUE TITLE
I have a bluetooth keyboard, just need DDC switch without the USB watchdog part

### ISSUE THREAD

**Issue by sdbruder** [haimgel/display-switch#13]
I'm using a bluetooth keyboard, can we just get the DDC switch part with no daemon-ization? I can execute it when the bluetooth keyboard is connected on macOS (using control Plane), so I only need the DDC switching part.

**Comment by haimgel** [comment]
I suggest checking out [ddcctl](https://github.com/kfix/ddcctl): I think it does what you want.
