### ISSUE TITLE
Support multiple command executions with `on_usb_<event>_execute`

### ISSUE THREAD

**Issue by bil0u** [haimgel/display-switch#133]
Hi there, thanks for your work on this project.

I'm using a custom version of m1ddc to send switching input commands to my displays when my USB switch is disconnected, and the binary needs to be called for each display.

It would be great to support execution of multiple commands when usb events are fired.

An easy implementation (tested) would be to split the command string on the `;` delimiter, and call each command successively.

---

https://github.com/haimgel/display-switch/blob/a5b76e0d04a84051b7fc6dac212143bce5760b41/src/display_control.rs#L180-L181

would be replaced by

```rust
for subcommand in execute_command.split(";") {
    let subcommand = subcommand.trim();
    if !subcommand.is_empty() {
        try_run_command(subcommand).unwrap_or_else(|err| error!("Error executing external command '{}': {}", subcommand, err));
    }
}
```

What do you think ?

**Comment by haimgel** [comment]
1. I just merged M1/M2/M3 support onto main, so this should no longer be neccessary.
2. In general, I'm not in favor of this feature (can always wrap individual commands in a batch file if needed).
