### ISSUE TITLE
Sceptre C35 InputSources 

### ISSUE THREAD

**Issue by klevermonicker** [haimgel/display-switch#136]
This is working halfway for me. I run a mac for work and a linux desktop for everything else. I can get display-switch working from mac into linux, but I cannot go the other way.

My desktop is on displayport1 (reported as 0x7) from display-switch.
My mac is on Hdmi1 (reported as 0x11) from display-switch.
Mac is intel based running Sonoma

my ini files are all using the raw the 0x notation. 

This is in the logs for the mac.
`06:45:34 [INFO] Monitored device ("291a:3369") is connected
06:45:34 [DEBUG] (1) display_switch::display_control: Input sources found for display 'Sceptre C35': InputSources { on_usb_connect: Some(Hdmi1(0x11)), on_usb_disconnect: Some(Custom(0x7)), on_usb_connect_execute: None, on_usb_disconnect_execute: None }
06:45:34 [WARN] Failed to get current input for display 'Sceptre C35': DDC/CI error: invalid DDC/CI length
06:45:34 [DEBUG] (1) display_switch::display_control: Setting display 'Sceptre C35' to Hdmi1(0x11)
06:45:34 [INFO] Display 'Sceptre C35' set to Hdmi1(0x11)`

I left out that I get this when running display-switch manually on the mac: 07:09:44 [ERROR] Failed to set display 'Sceptre C35' to Hdmi1(0x11) (MacOS kernel I/O error: -536870187)

I have no errors on the linux machine, it just sits there on Displayport.

Any ideas?

**Comment by haimgel** [comment]
Some monitors do not implement DDC controls correctly, or for all ports, unfortunately.
