### ISSUE TITLE
Homebrew version not working on M1 Mini (Mac OS Sequoia) - "libusb-1.0.0.dylib' (no such file)"

### ISSUE THREAD

**Issue by cryo-kronos** [haimgel/display-switch#152]
Is this broken on ARM Macs? I installed 1.40 via Homebrew (M1 Mini running Mac OS Sequoia) and then tried to launch it but that fails with the following message: 

`Library not loaded: /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib
  Referenced from: <597A8C75-B591-3A55-A419-AF55FE4E2A55> /opt/homebrew/Cellar/display_switch/1.4.0/bin/display_switch
  Reason: tried: '/opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib' (no such file)
`

**Comment by haimgel** [comment]
I might have missed a dependency in Homebrew config. Could you please do:
```
brew install libusb
```
and try again?

**Comment by cryo-kronos** [comment]
> I might have missed a dependency in Homebrew config. Could you please do:
> 
> ```
> brew install libusb
> ```
> 
> and try again?

Thank you, that worked but "brew install libusb" is a missing step. It's not mentioned in the readme. Is the homebrew formula supposed to install "libusb" automatically as a dependency?

**Comment by haimgel** [comment]
I updated the Brew formula, so going forward ,this should be fixed for new users (the dependency will be installed automatically).
