### ISSUE TITLE
Instructions on finding USB device ID

### ISSUE THREAD

**Issue by cocowalla** [haimgel/display-switch#16]
It will not be obvious to some how to find the USB device ID, so it would be great to add a section to the readme for this. Would you accept a PR for this? (I can do it for Windows, not MacOS tho)

**Comment by kcorey** [comment]
On a Mac...install home-brew.  (https://brew.sh). Use a regular keyboard not attached to the faux kvm.

Open a terminal.

brew install lsusb

$ lsusb > a
<switch on the usb>
$ lsusb > b
$ opendiff a b

The lines that are highlighted should show you which usb ID to pay attention to.

**Comment by haimgel** [comment]
@cocowalla of course, I'd gladly accept a PR for documentation improvements, I agree this info is missing.

**Comment by cocowalla** [comment]
Fixed by #23
