### ISSUE TITLE
Not switching to different input (same works) due to I2C bus error when using an active DisplayPort-to-HDMI adapter

### ISSUE THREAD

**Issue by Krischan** [haimgel/display-switch#19]
Reporting to document and for completeness sake as this appears to be an issue with the DP-HDMI adapter.

- Windows 10, 64 Bit, current on updates.
- Active DisplayPort to HDMI adapter
  - Accell DP to HDMI Adapter - DisplayPort 1.2 to HDMI 2.0 Active Adapter - 4K UHD @ 60Hz. Model number: B086B-011B). 
- The log shows two displays, which may be due to the adapter:
  - Generic PnP Monitor '#0' - 0x11 
  - GM107GL-A/2147881095:Lvds '# 1' - 0x11
- The adapter is detected as a relay by the NVidia drivers, which also prevents HDCP from working. 
- The name of my monitor (LG Ultra HD) is shown by the display driver and the ControlMyMonitor utility but not in the display-switch logs.

The programmatic display input switch works when the input is still the same. However, after a manual switch to another input switching back no longer works. The I2C signal no longer gets through causing an I2C error which gets logged. 

Case 1 - toggling the USB switch while input is already set to HDMI (0x11) (PC), i.e. setting to active input.
```
16:44:55 [DEBUG] (1) display_switch::app: Detected device change. Added device: "05e3:0612"
16:44:55 [INFO] Detected device we're looking for "05e3:0612"
16:44:55 [DEBUG] (1) display_switch::platform::display_control_ddc_hi: Setting display ''Generic PnP Monitor' #0' to 0x11
16:44:55 [INFO] Display 'Generic PnP Monitor' #0 set to 0x11
16:44:55 [DEBUG] (1) display_switch::platform::display_control_ddc_hi: Setting display ''GM107GL-A/2147881095:Lvds' #1' to 0x11
16:44:55 [INFO] Display 'GM107GL-A/2147881095:Lvds' #1 set to 0x11
16:44:56 [DEBUG] (1) display_switch::app: Detected device change. Added device: "05e3:0610"
16:46:11 [DEBUG] (1) display_switch::app: Detected device change. Added device: "0000:0000"
```

Case 2 - toggling USB switch when input is set to DisplayPort (Mac)
```
16:51:08 [DEBUG] (1) display_switch::app: Detected device change. Added device: "05e3:0612"
16:51:08 [INFO] Detected device we're looking for "05e3:0612"
16:51:08 [DEBUG] (1) display_switch::platform::display_control_ddc_hi: Setting display ''Generic PnP Monitor' #0' to 0x11
16:51:08 [ERROR] Failed to set display 'Generic PnP Monitor' #0 to 0x11 (Os { code: -1071241854, kind: Other, message: "An error occurred while transmitting data to the device on the I2C bus." })
16:51:08 [DEBUG] (1) display_switch::platform::display_control_ddc_hi: Setting display ''GM107GL-A/2147881095:Lvds' #1' to 0x11
16:51:08 [ERROR] Failed to set display 'GM107GL-A/2147881095:Lvds' #1 to 0x11 (I2c(Error))
16:51:08 [DEBUG] (1) display_switch::app: Detected device change. Added device: "05e3:0610"
```

**Comment by Krischan** [comment]
This issue seems to be specific to this LG monitor (or LG in general). It may have to do with aggressive energy saving mode switching.

**Comment by mariusmarais** [comment]
Seems like LG is particularly problematic with switching: https://github.com/rockowitz/ddcutil/issues/100
