### ISSUE TITLE
Please provide binaries

### ISSUE THREAD

**Issue by chx** [haimgel/display-switch#2]
Thanks _so much_ for this amazing software. Would it be an enormous hassle to provide binaries, I wonder?

**Comment by haimgel** [comment]
Thanks for @jrr we now have a pipeline with the binaries built on Github (which is safer of course). Note that MacOS binary is not signed/notarized, you'll have to jump through the hoops to make it run on Catalina or later.

**Comment by hannesfostie** [comment]
@haimgel where would one find these binaries? I was thinking it'd be under "releases" but that doesn't seem to be the case. Am I overlooking them?

**Comment by chx** [comment]
Under here https://github.com/haimgel/display-switch/actions?query=workflow%3Abuild it seems. There's a "release" for windows and mac after every commit.

**Comment by hannesfostie** [comment]
I just found them. I wonder if GH actions could put these under releases?

If not, maybe a readme entry would do to point people to the Actions tab and find them under build artifacts

**Comment by chx** [comment]
https://github.com/actions/upload-artifact/issues/21#issuecomment-628995879 is highly relevant. I
