### ISSUE TITLE
windows USBView for device detection

### ISSUE THREAD

**Issue by 0xpr03** [haimgel/display-switch#24]
Might be worth to add [USBView](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/usbview) for Windows to the possible tools to find your USB device.
Helped me to view the USB hierarchy and find out that the (authors) USB Switch itself disconnects on switch. Thus I can just detect the switch itself instead of my mouse.

**Comment by haimgel** [comment]
Ideally, I'm thinking of something in the app itself that could provide useful info in the logs. E.g. if it logged device name / type together with its vendor ID / device ID, that would probably be sufficient: use the USB switch to switch away and back, note the reported devices connected / disconnected, and voilla! 

However, if meanwhile you'd like to submit a patch against the readme, I won't be against it :-)
