### ISSUE TITLE
Failed to get current input for display (Support for DVI monitors)

### ISSUE THREAD

**Issue by erick-thompson** [haimgel/display-switch#25]
I'm trying to get this working with a Dell T2414H monitor hooked up by way of DP and DVI. I attempted to add DVI as a supported enum values, plus the raw value for DVI (0x03). In both cases, I get the following error.

19:25:10 [INFO] Display 'Generic PnP Monitor' #0 is currently set to 0x3
19:25:11 [INFO] Display 'Generic PnP Monitor' #1 is currently set to 0x3
19:25:11 [ERROR] Failed to get current input for display 'GP104-A/2147881091:Hdmi' #2: Ddc(InvalidChecksum)
19:25:11 [ERROR] Failed to get current input for display 'GP104-A/2147881092:Lvds' #3: Ddc(InvalidChecksum)

I'm not sure if this is an issue in display-switch or elsewhere. 

Note - I can use other DDC based programs, so I don't think it's a hardware/supportability issue.

**Comment by haimgel** [comment]
@erick-thompson failure to _get_ current input seems to be a display-switch issue. However: does it actually switch inputs, or do you get errors / failure to switch when it tries to switch as well?

**Comment by erick-thompson** [comment]
It does not switch inputs. I can't get any other logs/error in either debug or release build, so I suspect this error is fatal. Anything I can do to help debug?

**Comment by haimgel** [comment]
I've updated the current `master` with the improvements in DDC handling code on MacOS. I'd appreciate a test whether there are any changes: does the app read the current inputs now? Can it change them?
