### ISSUE TITLE
Support "waking up" monitors on switch under Linux

### ISSUE THREAD

**Issue by haimgel** [haimgel/display-switch#27]
The app should wake up the screens when it switches inputs under Linux, the same as it does under Windows and MacOS, e.g. implement [wake_displays](https://github.com/haimgel/display-switch/blob/master/src/platform/wake_displays.rs#L42).

**Comment by universal** [comment]
notes: https://unix.stackexchange.com/questions/124886/wake-monitor-from-sleep-remotely

```xset -display ${DISPLAY} dpms force on``` appears to be working on ubuntu 20.04

**Comment by pm215** [comment]
One potential issue with using 'xset' to trigger wakeup is that it needs the X display, and if you're running display-switch as root from systemd (as per the readme suggestion) then it doesn't have convenient access to the X display.

A possible alternate implementation would be to use /dev/uinput to simulate a USB keyboard or mouse and send a mouse-move or shift-key keypress. This sounds hairy but the implementation is pretty trivial in C (see https://www.kernel.org/doc/html/v4.12/input/uinput.html) and hopefully not too bad in rust (if you're prepared to trust a random crate off crates.rs then it's definitely pretty simple: https://docs.rs/crate/uinput/0.1.3). It would have the neat advantage that it would then not depend on whether you were running X or not.

**Comment by haimgel** [comment]
@pm215, neat! 
I'm not too concerned about moving the mouse to wake up screens, this is how this app already [does it on Windows](https://github.com/haimgel/display-switch/blob/master/src/platform/wake_displays.rs#L9-L19), and it works pretty well.

**Comment by haimgel** [comment]
Implemented in #126

**Comment by kllmanu** [comment]
@haimgel I'm curious if this also wakes up the host itself, e.g. if one switches from a linux to a windows machine which is currently asleep. But I guess one could always use wake-on-lan to do so.

**Comment by haimgel** [comment]
@kllmanu this does not wake the host itself. Obviously, this is only relevant for switching "away" from the host where display-switch is running. You could use the feature to run a command on "switch away" to execute wake-on-lan utility.
