### ISSUE TITLE
Support monitor selection

### ISSUE THREAD

**Issue by mmarb** [haimgel/display-switch#32]
I have a setup with 3 monitors, and i want to be able to only switch 1 monitors input using this tool. It seems to me this could be a vaild use case for others too, and therefor it would be nice if you could for example whitelilst the specfic monitors to switch in the configuration file.

**Comment by haimgel** [comment]
I just pushed a change that would support this (see README updates in master). Basically, you would do this: omit `on_usb_connect` and `on_usb_disconnect` from the global section, and only add these values to a per-monitor section that you _do_ want to switch. Something like this:

```ini
usb_device = "1050:0407"

[monitor1]
monitor_id = "dell"
on_usb_connect = "DisplayPort2"
on_usb_disconnect = "Hdmi1"
```
