### ISSUE TITLE
Support bluetooth as well?

### ISSUE THREAD

**Issue by dcarosone** [haimgel/display-switch#41]
I've just discovered this, and it seems really cool.

It seems to me that the same method could also work without the usb hub. Lots of bluetooth keyboards will pair with multiple devices and can switch connections between them. Monitorning for this connection appearing and disappearing could also trigger the same result!

**Comment by haimgel** [comment]
An interesting idea! I can see some possible issues, though:
1. BT connection/disconnection is usually pretty slow, comparing to USB... Would that be sufficiently fast, to be useful? I don't have such a keyboard to have a first-hand experience.
2. A cross-platform (windows/macos/linux) Bluetooth enumeration/plug&play detection is going to be challenging! My casual Googling didn't turn up anything useful, so quite a bit of development might be required here.

I'd be happy to accept PRs to support this functionality, but won't have time to implement this in the short-term.

**Comment by ZyztemeD** [comment]
Could HIDAPI be useful for this ? [](https://github.com/libusb/hidapi)

It detects both USB and BT HID devices and it is multiplatform.

**Comment by haimgel** [comment]
I looked into this, and while I might accept PRs, I won't implement this change myself:
* This library does not support plug-n-play notifications. This means polling, which is less efficient.
* This library is HID-only; currently, display-switch supports also non-HID USB devices. So this would be a regression for some folks...
