### ISSUE TITLE
[Feature Request] [Windows] Add icon to system tray

### ISSUE THREAD

**Issue by shanempope** [haimgel/display-switch#5]
I'm trying to add a feature to this and the one nice thing to have would be an icon in the system tray when the app is running. Right now I'm killing the app in Task Manager over and over.

potentially: https://github.com/qdot/systray-rs

**Comment by haimgel** [comment]
I'm quite opposed to polluting the system tray... In this specific case, there's no useful indication from the app, no user controls. I agree it's not really developer-friendly atm, but a tray icon is not an answer here.

**Comment by daniel5151** [comment]
I'm also interested in this feature (primarily as a dev loop improvement), and wouldn't mind looking into how to implement it as a PR.

Before doing that though, would you be interested in merging such a PR, with the condition that the icon would be _optional_ based on some configuration setting? i.e: something like `tray_icon = true` (where the default is off)
