### ISSUE TITLE
cannot find Windows binary

### ISSUE THREAD

**Issue by g1sm** [haimgel/display-switch#63]
Hi,

I'm not able to find the Windows binary anymore. It looks like the artifacts of the last build have expired, so the (Windows) binary is no longer available. Or am I looking in the wrong place?

![image](https://user-images.githubusercontent.com/43941940/121224252-aa1bfb00-c888-11eb-9f4e-760ec66b7f0c.png)

**Comment by haimgel** [comment]
@g1sm you were looking in the right place, it's just that the project hasn't been built in a while. I merged some PRs and now we have new artifacts: https://github.com/haimgel/display-switch/actions/runs/933750339#artifacts
