### ISSUE TITLE
Log file created, but is empty.

### ISSUE THREAD

**Issue by ChinmayTyagi** [haimgel/display-switch#67]
Hello, 
This looks like a great tool to switch between my work computer and PC, while saving some money. However, I'm having some trouble with setup.

I am on windows on both systems, with 2 monitors and a USB switch as my "USB device". 
Given a 2-monitor setup and USB hub as my device, I have created the following config file (all the way at bottom).
When I run the display_switch.ex (copied to AppData/roaming), a log file is created. However, this file is empty. Since I have no feedback, it's hard to know exactly where I am messing up.

Any advice? Thanks so much!

display-switch.ini:

usb_device = "1A40:0101"

[monitor1]
monitor_id = "GSM7706"
on_usb_connect = "Hdmi1"

[monitor2]
monitor_id = "LEN61E6"
on_usb_connect = "DisplayPort1"

**Comment by youngmit** [comment]
I am in nearly the exact situation. Two monitors, Windows. When running the exe, it quits immediately, no standard out, no contents in the log file.

**Comment by jordevorstenbosch** [comment]
> Actually, on Windows the app wasn't printing anything on the console ever. This is being fixed in the upcoming release, so the suggestion above would be valid when `1.1` is released.

It still doesn't put anything in the logfile on windows it seems.

Trough console I get the following though:

```PS
PS C:\Users\micro\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup> .\display_switch.exe
PS C:\Users\micro\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup> Error: failed to load configuration

Caused by:
    ParseIntError { kind: InvalidDigit }
```

**Comment by haimgel** [comment]
I think the "invalid digit" message is misleading, but the root cause is that `on_usb_connect = "Hdmi"` line is invalid. It needs to be `Hdmi1` or `Hdmi2` etc. The first thing the app does is parsing the config file, if that failed, it does not go further, this is the reason the log file is empty IMO.
