### ISSUE TITLE
[Feature Request] Add the ability to switch to a different monitor input when usb disconnected

### ISSUE THREAD

**Issue by shanempope** [haimgel/display-switch#7]
I actually wrote the code for this and it works, but I've never written rust before and I'm not sure how to make the extra configuration optional.
Here's the PR for anyone curious: https://github.com/shanempope/display-switch/pull/1/files

This way I only have to run it on one of my devices.

**Comment by haimgel** [comment]
That's a neat idea! I can see how this could be useful for many... I'll try to add something like this (in both Rust and Swift for completeness).

**Comment by kcorey** [comment]
Oh! My PR https://github.com/haimgel/display-switch/pull/20 only added it for Rust on my Mac. I don't know about Windows.

**Comment by B0rax** [comment]
That would be great for people like me with a personal computer and a company owned PC which I am not allowed to install software on

**Comment by bstag** [comment]
Seems to be the only way my monitors will work as they will not accept a request to switch if they are not on that connection. Both machines set to do this so it changes the monitor input from the original machine to the new machine instead of vise versa.

**Comment by GazzaHazza** [comment]
Any news on this?

**Comment by haimgel** [comment]
Going to look into this somewhen this or next week, most probably. As time permits.

**Comment by GazzaHazza** [comment]
> Going to look into this somewhen this or next week, most probably. As time permits.

Awesome! thanks!

**Comment by B0rax** [comment]
Thanks!! Works great 👍

**Comment by bstag** [comment]
Works very well thank you.
