### ISSUE TITLE
Failed to get current input

### ISSUE THREAD

**Issue by kurktchiev** [haimgel/display-switch#80]
So i have one monitor (Acer Predator) with two DisplayPorts, 2 HDMI and 1 USB-C. I am able to specify the DP ports not problem with 1 and 2. Running on Hdmi1 though I keep getting this error:
```
16:29:30 [INFO] Configuration loaded ("/Users/valhalla/Library/Preferences/display-switch.ini"): Configuration { usb_device: "1532:0046", default_input_sources: InputSources { on_usb_connect: Some(Hdmi1(0x11)), on_usb_disconnect: None, on_usb_connect_execute: None, on_usb_disconnect_execute: None }, monitor1: None, monitor2: None, monitor3: None, monitor4: None, monitor5: None, monitor6: None }
16:29:30 [ERROR] Failed to get current input for display 'X34 GS S/N 288360628': Io(-536870206)
```

This is running on OS X 10.15.7 (19H1519)

**Comment by jjordy** [comment]
I am also having this issue when on the mac side of my setup. But I get a `DDC Invalid Checksum`

**Comment by bustamelon** [comment]
Also using an Acer Predator here (34 GS) -- and I'm not able to set the USB-C input. README suggests that Type C input is usually self-identified as DisplayPort2, but what if there's already an actual DisplayPort2?

**Comment by haimgel** [comment]
Individual monitor support is hit-and-miss, unfortunately. Not something I can fix. I suggest trying different hex values for inputs, maybe your monitor uses a non-standard one.
