### ISSUE TITLE
Frame rate change

### ISSUE THREAD

**Issue by Tabiskabis** [haimgel/display-switch#81]
I have 2 Dell S2721DGF monitors connected to a Windows PC via HDMI at 144 Hz and a Mac laptop via DP at 120 Hz.
For the last few months, I've used a script for the Dell Display Manager application to switch inputs, and the refresh rates change to their respective max, as expected. 

Every second or third time when i let display-switch go from the PC to the laptop input, the refresh rate of one of the screens (always the same one) drops to 60 Hz and it takes a cable reconnect for the 120Hz to be recognized as valid refresh rate again.

I'll just work around the issue by running the old script on the PC, but i'd love to get rid of that, as for some reason it's much slower in issuing the input switch command than display-switch is.

**Comment by haimgel** [comment]
I wonder if "much slower" part is relevant to reliability here... I guess the platform is Windows, correct?

**Comment by Tabiskabis** [comment]
Whoops, grave mistake in my original post, now corrected.

The issue only happens when switching from PC to Mac, where the Mac version of display-switch commands the monitors to switch to DP (on_usb_connect = "DisplayPort1").

I have not tried using on_usb_disconnect on the windows PC, as the goal for me is to easily switch to the MacBook even when i'm running a different/temporary OS on the PC

**Comment by Tabiskabis** [comment]
Update for that: seems to be a timing issue on MacOS (i'm still on Mojave).
Issue solved by making on_usb_connect execute a script which issues the switch command in parallel (using ddcctl).
