### ISSUE TITLE
Load failed: 5: Input/output error

### ISSUE THREAD

**Issue by jcodesss** [haimgel/display-switch#85]
Mac Os Monterey(intel),
loading command  - `launchctl load ~/Library/LaunchAgents/dev.haim.display-switch.daemon.plist`
error -
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.

**Comment by haimgel** [comment]
Did you put the Plist file in that directory? What does `cat ~/Library/LaunchAgents/dev.haim.display-switch.daemon.plist` output?

**Comment by rahulparekh** [comment]
This usually happens if you already have it running. Try:
```
launchctl unload ~/Library/LaunchAgents/dev.haim.display-switch.daemon.plist
launchctl load ~/Library/LaunchAgents/dev.haim.display-switch.daemon.plist
```
