### ISSUE TITLE
Out of Range

### ISSUE THREAD

**Issue by blake-mealey** [haimgel/display-switch#86]
I've been getting an "Out of Range" monitor UI blocking the middle of my screen after display-switch switches from HDMI (PC) to DisplayPort (Mac). Any ideas on how to troubleshoot/fix this?

Thanks

**Comment by haimgel** [comment]
Don't know for sure, but I wonder what happens when you do the same switch using the buttons on your monitor? 
Also, does the monitor actually switch to the right input, and then you get this message, or it does not switch, and the message is on top of a black screen?

If it's the later, then it's probably because DisplayPort is not the right port to choose in `display-switch`. These labels are somewhat arbitrary, and monitor vendors do not always follow conventions. It makes sense to switch manually, and then run `display-switch`, it will report the _current_ setting if it can detect it, it might be *not* DisplayPort after all.

**Comment by lauhayden** [comment]
I'm getting this problem as well with my LG 27GL83A-B. This issue on the `ddcutil` repo seems related: https://github.com/rockowitz/ddcutil/issues/102

> Don't know for sure, but I wonder what happens when you do the same switch using the buttons on your monitor?

Switching via buttons on monitor works, and if I'm getting the "Out of Range" UI, switching away and back using the physical buttons fixes it.

> Also, does the monitor actually switch to the right input, and then you get this message, or it does not switch, and the message is on top of a black screen?

It switches, then the message appears on top of the new input. It also happens using `ddcutil setvcp 60 <value>`, so it's a problem with the monitor and not `display-switch`.

**Comment by lauhayden** [comment]
Just did some more testing:

- the LG monitor only supports DDC on the input that is currently selected
- switching Displayport1 -> HDMI1 (commanded by the Displayport1 input) gave no issues
- switching HDMI1 -> Displayport1 (commanded by the HDMI1 input) gave the "Out of Range" problem
- this happens whether or not Freesync is on
- using the on-screen display (physical buttons) after switching via DDC results in the UI still showing the old input. Reselecting current input (HDMI1 -> Displayport1 commanded by DDC, then reselect Displayport1 via OSD) clears the "Out of Range" error

**Comment by haimgel** [comment]
Yeah,  TBH this looks like some kind of firmware bug in the LG monitor. Not uncommon, unfortunately. The manufacturers rarely test DDC/CI properly, in my opinion, especially in consumer-grade monitors.

**Comment by nichcuta** [comment]
I have a similar setup with a LG 27GL83A-B Monitor and indeed had the same issues described above although after some config changes it seems to be working reliably.

Setup and Config:
```
PC1: Windows 10
PC2: Macbook Pro - Catalina

PC1 --> DP cable -->  LG 27GL83A-B Monitor
PC1 --> DP to HDMI Cable --> Dell P2720DC Monitor

PC2 --> USB-C to HDMI Cable --> LG 27GL83A-B Monitor
PC2 --> USB-C Cable --> Dell P2720DC Monitor
```

Config on PC1
```
usb_device = "2972:0047"

[monitor1]
monitor_id = "ULTRAGEAR"    # Logitech
on_usb_disconnect = "hdmi1"

[monitor2]
monitor_id = "P2720DC"
on_usb_connect = "hdmi1"  
```

Config on PC2
```
usb_device = "2972:0047"

[monitor1]
monitor_id = "27GL850"    # Logitech
on_usb_connect = 17
on_usb_disconnect = 15

[monitor2]
monitor_id = "P2720DC"
on_usb_connect = 27
on_usb_disconnect = 17
```

The only issue I am facing is with the P2720DC Dell monitor. For some reason it is capable of switching from PC1 to PC2 and back to PC1 but upon trying to change from PC1 to PC2 again, the monitor simply says "No source detected on USB-C". Trying to figure this out but cant understand why this happens on the second cycle. If you have any suggestions, please do tell.

Hope the above config helps you :)

**Comment by nichcuta** [comment]
The P2720DC monitor goes in soft power off mode during the second cycle (although using on_usb_connect) and the only fix I found was to check for power state, revert to original source (HDMI), wait some seconds, and change back source to USB-C. Below is some basic logic written in python, but was wondering is such logic can be implemented in display-switcher as an enhancement, perhaps thats a question for @haimgel?

```
from monitorcontrol import get_monitors
from monitorcontrol.monitorcontrol import InputSourceValueError
from time import sleep

for monitor in get_monitors():
    with monitor:
        sleep(5)
        curr_mon_power = monitor.get_power_mode()
        if "PowerMode.off_soft" == str(curr_mon_power):
            monitor.set_input_source(17)    # Reverting back to HDMI Source
            sleep(3)
            monitor.set_input_source(27)    # Set Source to USB-C
```

**Comment by lauhayden** [comment]
@nichcuta 

> I have a similar setup with a LG 27GL83A-B Monitor and indeed had the same issues described above although after some config changes it seems to be working reliably.

Huh, with that specific connect/disconnect setup on each computer it actually works without the "Out of Range" error! Thanks so much! I did notice that there was an additional step required: the manual input selection using the monitor's buttons needs to be set to "DisplayPort". This setup also does not work for a bizarre reason without the `on_usb_connect = "Hdmi1"` on the HDMI computer, which is ostensibly redundant.

**Comment by nichcuta** [comment]
> This setup also does not work for a bizarre reason without the on_usb_connect = "Hdmi1" on the HDMI computer, which is ostensibly redundant.

Yea, the configuration seems messy at best, but hey it works. You are right, forgot to mention that my primary PC is connected via DP and hence usually switch from it first.

Have not encountered the sleep/wake issue, but hopeful that it can be mitigated via code like the above mentioned solution for the P2720DC monitor.
