### ISSUE TITLE
Windows 10 Compile Error: failed to run custom build command for `uninitialized v0.0.2`

### ISSUE THREAD

**Issue by adamklaff** [haimgel/display-switch#88]
When attempting to compile on Windows 10, I receive the following error:

> 
> cargo build --release
>    Compiling winapi v0.3.9
>    Compiling proc-macro2 v1.0.21
>    Compiling autocfg v1.0.1
>    Compiling unicode-xid v0.2.1
>    Compiling libc v0.2.77
>    Compiling syn v1.0.40
>    Compiling serde_derive v1.0.115
>    Compiling serde v1.0.115
>    Compiling bitflags v1.2.1
>    Compiling cfg-if v0.1.10
>    Compiling void v1.0.2
>    Compiling crc32fast v1.2.0
>    Compiling memchr v2.3.3
>    Compiling ryu v1.0.5
>    Compiling cfg-if v1.0.0
>    Compiling rle-decode-fast v1.0.1
>    Compiling adler32 v1.2.0
>    Compiling linked-hash-map v0.5.3
>    Compiling uninitialized v0.0.2
>    Compiling take_mut v0.2.2
>    Compiling log v0.4.11
>    Compiling version_check v0.9.2
>    Compiling serde v0.8.23
>    Compiling adler v1.0.2
>    Compiling pkg-config v0.3.18
>    Compiling lexical-core v0.7.6
>    Compiling vcpkg v0.2.10
>    Compiling gimli v0.23.0
>    Compiling lazy_static v1.4.0
>    Compiling cc v1.0.59
>    Compiling failure_derive v0.1.8
>    Compiling regex-syntax v0.6.18
>    Compiling serde_json v1.0.57
>    Compiling rustc-demangle v0.1.21
>    Compiling static_assertions v1.1.0
>    Compiling object v0.22.0
>    Compiling arrayvec v0.5.1
>    Compiling dtoa v0.4.6
>    Compiling ddc-hi v0.3.0
>    Compiling itoa v0.4.6
>    Compiling anyhow v1.0.44
>    Compiling widestring v0.3.0
>    Compiling rust-ini v0.13.0
>    Compiling paste v1.0.1
>    Compiling shell-words v1.0.0
>    Compiling mccs v0.1.0
>    Compiling yaml-rust v0.4.4
>    Compiling num-traits v0.2.12
>    Compiling miniz_oxide v0.4.4
>    Compiling num-integer v0.1.43
>    Compiling thread_local v1.0.1
> error: failed to run custom build command for `uninitialized v0.0.2`
> 
> Caused by:
>   could not execute process `C:\Users\xxx\display-switch\target\release\build\uninitialized-f4d89252e48548c1\build-script-build` (never executed)
> 
> Caused by:
>   The process cannot access the file because it is being used by another process. (os error 32)
> warning: build failed, waiting for other jobs to finish...
> error: build failed

**Comment by haimgel** [comment]
I just checked and the builds on Github runners are working fine (https://github.com/haimgel/display-switch/runs/5081385728), so I'm pretty sure it's something on your machine. Some overzealous antiviruses could interfere like this, for example.
